version: '3'

services:
  react-app:
    build:
      context: . #context to look for Dockerfile in
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules #do not mount node_modules
      - .:/frontend/app #mount everyrhing in current to /app
